"""SQS consumer — fires StartOutboundVoiceContact after the 22-second delay.

Each SQS message corresponds to one agent dispatch. The message was enqueued
by handler_consumer.py with DelaySeconds=22, which ensures First Orion's
branding window (10–30s) is active when the SIP INVITE is sent.

Throttle: StartOutboundVoiceContact is capped at 2 RPS / 5 burst per account+region.
Lambda reserved concurrency is set to 2 in the CDK stack.

Re-push on throttle: when Connect throttles us and SQS will retry after the
visibilityTimeout (180s), the original First Orion branding window is already
expired. We re-dispatch the INFORM push immediately before re-raising so the
retried dial lands inside a fresh branding window.
"""
from __future__ import annotations

import json
import logging
import os

import boto3

from agent_lock import AgentLock
from campaign_queue import CampaignQueue
from connect_caller import ConnectCaller
from first_orion_client import FirstOrionClient

logger = logging.getLogger()
logger.setLevel(logging.INFO)

_CAMPAIGN_QUEUE_TABLE = os.environ["CAMPAIGN_QUEUE_TABLE"]
_AGENT_LOCK_TABLE = os.environ["AGENT_LOCK_TABLE"]
_FIRSTORION_SECRET_NAME = os.environ["FIRSTORION_SECRET_NAME"]
_CW_NAMESPACE = "VipConnect/ProgressiveDialer"

_queue_store: CampaignQueue | None = None
_lock_store: AgentLock | None = None
_fo_client: FirstOrionClient | None = None
_cw_client = None


def _get_queue() -> CampaignQueue:
    global _queue_store
    if _queue_store is None:
        _queue_store = CampaignQueue(_CAMPAIGN_QUEUE_TABLE)
    return _queue_store


def _get_lock() -> AgentLock:
    global _lock_store
    if _lock_store is None:
        _lock_store = AgentLock(_AGENT_LOCK_TABLE)
    return _lock_store


def _get_fo() -> FirstOrionClient:
    global _fo_client
    if _fo_client is None:
        _fo_client = FirstOrionClient.build_from_secret(_FIRSTORION_SECRET_NAME)
    return _fo_client


def _get_cw():
    global _cw_client
    if _cw_client is None:
        _cw_client = boto3.client("cloudwatch")
    return _cw_client


def _emit_metric(metric_name: str, value: float = 1.0) -> None:
    """Emit a custom metric to VipConnect/ProgressiveDialer namespace.

    Failures are logged but not raised — metric emission must never abort a dispatch.
    """
    try:
        _get_cw().put_metric_data(
            Namespace=_CW_NAMESPACE,
            MetricData=[{"MetricName": metric_name, "Value": value, "Unit": "Count"}],
        )
    except Exception as exc:
        logger.warning("Failed to emit metric %s: %s", metric_name, type(exc).__name__)


def _process_message(body: dict) -> None:
    agent_arn = body["agentArn"]
    queue_arn = body["queueArn"]
    campaign_id = body["campaignId"]
    contact_sk = body["contactSk"]
    instance_id = body["instanceId"]
    contact_flow_id = body["contactFlowId"]
    source_phone = body["sourcePhone"]
    # correlationId was generated by the consumer at dequeue time and propagated here
    # so both Lambdas share the same trace ID in CloudWatch. Fallback for older messages.
    correlation_id = body.get("correlationId") or contact_sk[:8]

    # Extract queue ID from ARN (last segment)
    queue_id = queue_arn.split("/")[-1]

    # Read destination phone from DynamoDB — PHI is not carried in the SQS message body.
    # This keeps the phone number out of SQS and the DLQ (14-day retention).
    destination_phone = _get_queue().get_phone(campaign_id, contact_sk)
    if not destination_phone:
        logger.warning(
            "Contact not found or missing phone campaign_id=%s correlation_id=%s",
            campaign_id,
            correlation_id,
        )
        # Reset contact so it can be retried by the next available agent.
        try:
            _get_queue().reset_to_pending(campaign_id, contact_sk)
        except Exception as e:
            logger.error(
                "reset_failed_on_missing_phone correlation_id=%s error=%s",
                correlation_id,
                type(e).__name__,
            )
        # Release the agent lock — the agent is free to take the next dispatch.
        try:
            _get_lock().release(agent_arn)
        except Exception as e:
            logger.error(
                "lock_release_failed_on_missing_phone correlation_id=%s error=%s",
                correlation_id,
                type(e).__name__,
            )
        return

    caller = ConnectCaller(
        instance_id=instance_id,
        contact_flow_id=contact_flow_id,
    )
    result = caller.dial(
        destination_phone=destination_phone,
        queue_id=queue_id,
        source_phone=source_phone,
        # contact_sk is a deterministic idempotency key — Connect deduplicates within ~7min,
        # preventing double-dials if SQS redelivers the message on Lambda failure.
        client_token=contact_sk,
    )

    if result.success:
        _get_queue().mark_dialed(campaign_id, contact_sk, result.contact_id)
        logger.info(
            "Dial success campaign_id=%s contact_id=%s correlation_id=%s",
            campaign_id,
            result.contact_id,
            correlation_id,
        )
        # Lock purpose: prevent double-dispatch on the same Available event.
        # Once the agent is in a call (mark_dialed succeeded), release the lock
        # so it is eligible for the next dispatch after the call ends.
        # Non-critical: TTL (600s) will auto-release if this call fails.
        try:
            _get_lock().release(agent_arn)
        except Exception as e:
            logger.warning(
                "lock_release_failed_post_dial correlation_id=%s error=%s",
                correlation_id,
                type(e).__name__,
            )
    elif result.throttled or result.error_code == "TooManyRequestsException":
        # Throttle: raise immediately — do NOT reset or release the lock.
        # Releasing the lock here would allow the next agent-available event to
        # re-dequeue the same contact and fire a second First Orion push before
        # this SQS message is redelivered by the visibility timeout.
        # The lock TTL will expire naturally; SQS visibility timeout retries the call.
        logger.warning(
            "Dial throttled campaign_id=%s correlation_id=%s — SQS will retry",
            campaign_id,
            correlation_id,
        )
        _emit_metric("ConnectThrottleCount")
        # Re-push First Orion so the branding window is fresh for the retry.
        # The SQS visibilityTimeout (180s) far exceeds First Orion's 30s window,
        # so the original push is always stale by the time SQS redelivers.
        try:
            _get_fo().push(a_number=source_phone, b_number=destination_phone)
            logger.info("First Orion re-pushed on throttle retry correlation_id=%s", correlation_id)
        except Exception as fo_err:
            logger.warning(
                "first_orion_repush_failed_on_throttle correlation_id=%s error=%s",
                correlation_id,
                str(fo_err),
            )
        raise RuntimeError("StartOutboundVoiceContact throttled — SQS will retry")
    else:
        # Permanent failure: reset + release but ack the message (do not raise).
        # The contact re-enters the queue for the next available agent.
        logger.warning(
            "Dial failed error_code=%s campaign_id=%s correlation_id=%s",
            result.error_code,
            campaign_id,
            correlation_id,
        )
        try:
            _get_queue().reset_to_pending(campaign_id, contact_sk)
        except Exception:
            logger.error("Failed to reset contact to PENDING correlation_id=%s", correlation_id)
        # Release agent lock so the next AVAILABLE event can dispatch
        _get_lock().release(agent_arn)


def lambda_handler(event: dict, _context) -> dict:
    for record in event.get("Records", []):
        body = json.loads(record["body"])
        # RuntimeError from throttle is intentionally NOT caught here — it must
        # propagate so Lambda returns a partial-batch failure and SQS redelivers.
        _process_message(body)
    return {"status": "ok"}
